#!/bin/bash

# Examine user input
export USER_ACTION="${1}"

case $USER_ACTION in

  --cpu | -c )
    ACTION="cpu"
    ;;

  --memory | -m )
    ACTION="memory"
    ;;

    system | -s )
    ACTION="system"
    ;;

  --help | -h )
    ACTION="help"
    ;;

  --about | -a )
    ACTION="about"
    ;;


  *)
    ACTION="main"
    ;;
esac

############################################
#                                          #
#        Let's Grab the infromations       #
#                                          #
############################################
# CPU Info Variables
CPU_MODEL="$(lscpu | grep -oP 'Model name:\s*\K.+')"
CPU_CORES="$(cat /proc/cpuinfo | grep processor | wc -l)"
CPU_THREADS="$(lscpu | grep -oP 'Thread\(s\) per core:\s*\K.+')"
CPU_THREADS_TOTAL="$(($CPU_THREADS * $CPU_CORES))"                                     #
CPU_USAGE=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')

# Memory Info Variables
MEM_TOTAL_RAW=$(grep MemTotal /proc/meminfo | sed -r 's/^MemTotal:       //' | sed -e 's/kB//')
MEM_TOTAL=$((MEM_TOTAL_RAW / 1024))
MEM_USAGE="$(free | grep Mem | awk '{print $3/$2 * 100.0}')"

# System Info Variables
SYS_TYPE=$(uname -m)
SYS_REL="$(lsb_release -d | cut -d ':' -f 2 | sed -e 's/^[[:space:]]*//')"
SYS_KERNEL_NAME=$(uname -s)
SYS_KERNEL_REL=$(uname -r)
SYS_KERNEL_VER="${SYS_KERNEL_NAME} ${SYS_KERNEL_REL}"

# Network Info Variables
PUBLIC_IP="$(wget -qO - icanhazip.com)"

# Session Info Variables
SES_TERM=${TERM}
SES_SHELL=${SHELL}

# Machine Info Variables
MACHINE_UPTIME=$(uptime -p | sed 's/up //')

# Display Info Variables
DISPLAY_RES=$(xrandr |awk '/\*/ {print $1}')


function do_cpu() {
    echo -e "=========================================================="
    echo -e "                  Akebi - CPU Information                 "
    echo -e "=========================================================="
    echo -e "CPU Model         :  ${CPU_MODEL}"
    echo -e "CPU Core(s)       :  ${CPU_CORES} Core(s)"
    echo -e "CPU Usage         :  ${CPU_USAGE}%"
    echo -e "=========================================================="
    echo -e " "
}

function do_memory() {
    echo -e "=========================================================="
    echo -e "                Akebi - Memory Information                "
    echo -e "=========================================================="
	echo -e "Memory Total      :  ${MEM_TOTAL} MB"
	echo -e "Memory Usage      :  ${MEM_USAGE}%"
    echo -e "=========================================================="
    echo -e " "
}

function do_system() {
    echo -e "=========================================================="
    echo -e "                Akebi - System Information                "
    echo -e "=========================================================="
	echo -e "Installed System  :  ${SYS_REL}"
	echo -e "System Type       :  ${SYS_TYPE}"
	echo -e "Kernel Version    :  ${SYS_KERNEL_VER}"
	echo -e "Terminal          :  ${SES_TERM}"
	echo -e "Shell             :  ${SES_SHELL}"
	echo -e "Uptime            :  ${MACHINE_UPTIME}"
    echo -e "=========================================================="}
    echo -e " "
}

function do_help() {
    echo -e "This is Akebi! A simple bash scipt to show your Linux System Information"
    echo -e " "
    echo -e "Usage: akebi [OPTION]"
    echo -e " "
    echo -e "Available Options:"
    echo -e " "
    echo -e "  -a, --about    Show About Akebi"
    echo -e "  -c, --cpu      Show Your CPU infromation"
    echo -e "  -h, --help     Show Help page. You are actually readong it right now!"
    echo -e "  -m, --memory   Show Your Memory infromation"
    echo -e "  -m, --system   Show Your System infromation"
    echo -e " "
}

function do_about() {
    echo "Akebi - A Simple Bash Script to show your System Information"
    echo -e " "
}

function do_main() {
	# The main interface
	echo -e "=========================================================="
	echo -e "                Akebi - System Information                "
	echo -e "=========================================================="
	echo -e "CPU Model         :  ${CPU_MODEL}"
	echo -e "CPU Core(s)       :  ${CPU_CORES} Core(s)"
	echo -e "CPU Usage         :  ${CPU_USAGE}%"
	echo -e "Memory Total      :  ${MEM_TOTAL} MB"
	echo -e "Memory Usage      :  ${MEM_USAGE}%"
	echo -e "Installed System  :  ${SYS_REL}"
	echo -e "System Type       :  ${SYS_TYPE}"
	echo -e "Kernel Version    :  ${SYS_KERNEL_VER}"
	echo -e "Public IPA Addr   :  ${PUBLIC_IP}"
	echo -e "Terminal          :  ${SES_TERM}"
	echo -e "Shell             :  ${SES_SHELL}"
	echo -e "Uptime            :  ${MACHINE_UPTIME}"
	echo -e "Screen Resolution :  ${DISPLAY_RES}"
	echo -e "=========================================================="
    echo -e " "
}

do_${ACTION}
