name: Script Testing
on:
  push:
    branches: [ '*' ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Download Setup script
        uses: actions/checkout@v2

      - name: Install Akebi
        run: ./install.sh

      - name: Test Akebi
        run: akebi

  macOS:
    runs-on: macos-latest
    environment: Actions
    steps:
      - name: Download Setup script
        uses: actions/checkout@v2

      - name: Test Akebi
        run: ./akebi